begin;
select plan(10);
select has_table('public', 'profiles', 'profiles exists');
select has_table('public', 'groups', 'groups exists');
select has_table('public', 'group_members', 'group_members exists');
select has_table('public', 'restaurants', 'restaurants exists');
select has_table('public', 'ratings', 'ratings exists');
select has_table('public', 'category_prefs', 'category_prefs exists');
select has_table('public', 'api_usage', 'api_usage exists');
select has_column('public', 'ratings', 'snoozed_until', 'ratings snooze exists');
select col_type_is('public', 'ratings', 'snoozed_until', 'timestamp with time zone', 'snooze is timestamptz');
select col_is_unique('public', 'groups', 'invite_code', 'invite code is unique');
select * from finish();
rollback;
